# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.runs/synth_1/.Xil/Vivado-9164-DESKTOP-7CFQ9ND/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/20250421_RISC_V_APB_RAM_GPIO {
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/sources_1/imports/20250421_RISC_V_APB_RAM_GPIO/APB_Master.sv
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/sources_1/imports/20250421_RISC_V_APB_RAM_GPIO/APB_Slave.sv
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/sources_1/imports/20250421_RISC_V_APB_RAM_GPIO/defines.sv
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/sources_1/imports/20250421_RISC_V_APB_RAM_GPIO/ControlUnit.sv
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/sources_1/imports/20250421_RISC_V_APB_RAM_GPIO/DataPath.sv
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/new/GPIO.sv
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/sources_1/imports/20250421_RISC_V_APB_RAM_GPIO/RV32I_Core.sv
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/sources_1/new/fndController.sv
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/sources_1/imports/20250421_RISC_V_APB_RAM_GPIO/gpi.sv
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/sources_1/imports/20250421_RISC_V_APB_RAM_GPIO/ram.sv
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/sources_1/imports/20250421_RISC_V_APB_RAM_GPIO/rom.sv
      C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.srcs/sources_1/imports/sources_1/imports/20250421_RISC_V_APB_RAM_GPIO/MCU.sv
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.runs/synth_1/.Xil/Vivado-9164-DESKTOP-7CFQ9ND/realtime/MCU_synth.xdc
    rt::sdcChecksum
    set rt::top MCU
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/CPU_Harman/20250423_RISC_V_CPU_FND_COUNTER/20250423_RISC_V_CPU_FND_Counter.runs/synth_1/.Xil/Vivado-9164-DESKTOP-7CFQ9ND/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
